name: 'Tests: E2E'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  tests-e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          # prettier-ignore
          key: Linux-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: Linux-playwright-
      - uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          # prettier-ignore
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 6.0.2
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: pnpm i
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Test
        run: pnpm run test
        env:
          # prettier-ignore
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
