name: 'Tests: Unit'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key:
            # prettier-ignore
            ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 8.0.0
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
        env:
          # prettier-ignore
          UPSTASH_REDIS_REST_URL : ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN : ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          PUBLIC_FATHOM_URL: ${{ secrets.PUBLIC_FATHOM_URL }}
          PUBLIC_FATHOM_ID: ${{ secrets.PUBLIC_FATHOM_ID }}
      - name: Test
        run: pnpm run test:ci
