name: 'Tests: Unit'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4
        with:
          version: 9.x
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
      - uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          # prettier-ignore
          key: ${{ runner.os }}-deps-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-deps-
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
        env:
          # prettier-ignore
          TURSO_DB_URL: ${{ secrets.TURSO_DB_URL }}
          TURSO_DB_AUTH_TOKEN: ${{ secrets.TURSO_DB_AUTH_TOKEN }}
          TURSO_SYNC_URL: ${{ secrets.TURSO_SYNC_URL }}
          PUBLIC_FATHOM_URL: ${{ secrets.PUBLIC_FATHOM_URL }}
          PUBLIC_FATHOM_ID: ${{ secrets.PUBLIC_FATHOM_ID }}
      - name: Test
        run: pnpm run test:ci
